language: cpp
compiler:
- g++
os:
- linux
install:
  - sudo pip install codecov
script:
- make
- make test
- make gcov
branches:
  only:
  - master
after_success:
  - codecov -t 3ceed7df-9722-46c6-bb13-884efc4467c3 -X gcov
